### ISSUE TITLE
hainging on react-native eject

### ISSUE THREAD

**Issue by ramyareye** [pmadruga/react-native-clean-project#16]
Hello

I upgraded from 3.0.0 to 3.2.1 and tried `react-native eject` but it hangs on `info Generating the Android folder.`

Could you please check it ?

Regards

**Comment by pmadruga** [comment]
Hi,

Can you provide more details, such as a log, node version, react native version and whether you are using yarn or npm?

Thanks


________________________________

**Comment by ramyareye** [comment]
I just did `react-native init rn` and `yarn add -D react-native-clean-project` and tried `react-native eject` 
it passes `info Generating the iOS folder.`  well but stucks on `info Generating the Android folder.`

rn : 0.59.8
yarn : 1.15.2
node : 11.11.0

**Comment by pmadruga** [comment]
This is in an expo project then?

**Comment by ramyareye** [comment]
No I don't use expo

**Comment by pmadruga** [comment]
Why the eject then?

**Comment by ramyareye** [comment]
I'm trying to build something on top of RN and I decided to include this package, I have to do eject to be sure of everything goes right every time :(

**Comment by pmadruga** [comment]
Just so I can replicate it, did you follow the steps here? https://facebook.github.io/react-native/docs/getting-started.html

Or form elsewhere, considering the usage of 'eject'.

**Comment by ramyareye** [comment]
I understand, but in my case I need that eject thing and there is a problem with this package and at the time I cannot find out why.
I hope I can make a time for it to find out.

**Comment by pmadruga** [comment]
Do you have anymore info you can provide? It's a bit hard to replicate it with the current info.
