### ISSUE TITLE
Xcode build cache not cleaned

### ISSUE THREAD

**Issue by mikehardy** [pmadruga/react-native-clean-project#18]
Hello there again good sir :-)

I just had a problem with react-native-firebase after making some changes there that removed whole files. Turns out Xcode has some more secret state that sometimes needs to be blown away, but it’s not done (yet) by react-native-clean-project

https://github.com/invertase/react-native-firebase/issues/2269#issuecomment-506135988
https://gist.github.com/maciekish/66b6deaa7bc979d0a16c50784e16d697

```bash
killall Xcode
xcrun -k
xcodebuild -alltargets clean
rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache"
rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang.$(whoami)/ModuleCache"
rm -rf ~/Library/Developer/Xcode/DerivedData/*
rm -rf ~/Library/Caches/com.apple.dt.Xcode/*
```

**Comment by mikehardy** [comment]
Following these steps fixed an otherwise-mysterious issue where iOS builds worked in debug and release, but not archive. Would have been fiendish to figure out without knowing of them, this could solve a tough class of problems for people

**Comment by pmadruga** [comment]
Thanks @mikehardy 👍
