### ISSUE TITLE
Doesn't work for Windows

### ISSUE THREAD

**Issue by xliank** [pmadruga/react-native-clean-project#24]
rm Commands only work for MacOS & Linux. 
Thanks

![Untitled](https://user-images.githubusercontent.com/19347346/62420924-71c39880-b6c4-11e9-8bd0-89a3933f1c56.png)

**Comment by pmadruga** [comment]
Thanks for raising the issue. I currently don't own a windows machine to test this, so I'm welcoming all PR's on this. 👍

**Comment by yfunk** [comment]
This is still an issue for me on my windows machine. Did anyone find a fix or workaround?

**Comment by KrisLau** [comment]
Problem still occurs on windows
