### ISSUE TITLE
prefer ./gradlew clean to rm build folder

### ISSUE THREAD

**Issue by wilau2** [pmadruga/react-native-clean-project#36]
I ran into an issue installing rn-fetch-blob. 

https://github.com/joltup/rn-fetch-blob/issues/422

I needed to run `./gradlew clean`. I don't think that removing the android build folder is enough to "clean" the project. 

Thoughts?

**Comment by wilau2** [comment]
#38

**Comment by aniravi24** [comment]
I'd be interested in this! Does this also clean the build folder? I believe this tool also uses the wrong directory - in my project, it looks like the outputs go to android/app/build, not android/build.

**Comment by pmadruga** [comment]
Hi, I've been locked out of my account but I'm back so I'll look at this and other issues as soon as I have the time.

**Comment by pmadruga** [comment]
hey @wilau2 any reason why you closed your PR?

**Comment by pmadruga** [comment]
Merged PR into master.
