### ISSUE TITLE
Enhancement - ability to clean user-level pod cache

### ISSUE THREAD

**Issue by mikehardy** [pmadruga/react-native-clean-project#42]
We just ran into an issue on react-native-firebase that was resolved by deleting the local cocoapods cache in the user's directory like so:

`rm -fr ~/.cocoapods/repos/trunk`

https://github.com/invertase/react-native-firebase/issues/3305#issuecomment-600459982

Might be nice to have an option to '--wipe-pods-user-cache' or similar?

**Comment by mikehardy** [comment]
Here's the basis for the fix: https://github.com/CocoaPods/CocoaPods/issues/9260#issuecomment-542586026

**Comment by pmadruga** [comment]
Wouldn't it make more sense to just wipe the entire `~/.cocoapods` folder?

**Comment by mikehardy** [comment]
I just wasted a fair bit of time yesterday with cocoapods cache corruption in ~/Library/Cache/CocoaPods (delete possible via `pod cache clean --all`) as well. Lost hours really, quite painful.

I think purging ~/.cocoapods and `pod cache clean --all` would be good additions, and I'd do a PR if you'd accept it @pmadruga ?

Deleting these will result in a great deal of network traffic to rebuild state so I would have them default to off in the "auto" scheme and only available via toggles or interactive response, personally, but open to suggestion on that.

**Comment by pmadruga** [comment]
A PR is more than welcome, thanks.

I believe the "auto" mode should induce the cleanest state, and the toggles to make it less clean. But I'm flexible on that one 👍🏼

**Comment by mikehardy** [comment]
I will defer to your taste in your module (and I am sympathetic to that anyway - clean should be *clean* :-) ). Okay I'll post up a PR for a truly clean cocoapods situation. If there is a convenient place to mention to the user that it implies a large network transfer cost in the future to rebuild the cache (like, in docs or if there is already CLI messaging) I'll do that so it's not a shock, or at least not an unknown one :)

**Comment by pmadruga** [comment]
Sounds like a great idea @mikehardy . Happy to review that PR.

**Comment by mikehardy** [comment]
I am still planning on doing this, just collecting ideas here from user reports of what worked for them as they fixed pod errors, 

here's another possibly-needed command: `pod repo remove trunk`, c.f. https://github.com/invertase/react-native-firebase/issues/4710#issuecomment-752683760

**Comment by mikehardy** [comment]
Just noting that @gilbertl [confirmed](However, I ran and checked just now and pod cache clean --all does remove the "~/Library/Cache/Cocoapods/pods" directory.

) `pod cache clean --all` is a valid command to clean the directory that bit me, thanks Gilbert

**Comment by mikehardy** [comment]
Out of the 3 ideas, I researched and learned that if we purge `~/.cocoapods` it means `pod repo remove trunk` is unnecessary, as that would just be affecting state within `~/.cocoapods` - it is a subset.

So I posted a PR that just did `rm -rf ~/.cocoapods` and `pod cache clean --all`

**Comment by pmadruga** [comment]
Thanks @mikehardy - PR approved with one commend.
